
@startuml


    |Користувач|
        start
        : Натискає на кнопку\n редагування артефакту;
    |Система|
        : Повертає модальне \nвікно для редагування \n артефакта;
        
    |Користувач|
        : В залежності від типу \nартефакта редагує \nвідповідним способом;
        : Натискає кнопку "Обновити";
    |Система|
        : Зберігає зміни артефакту;
        note right #ffaaaa
        <b> Можливо
        <b> EX_AR_3.1
        end note
        : Повертає повідомлення \nпро успішне редагування;
    |Користувач|
        stop;

    right footer
        Аналітичний портал. Модель прецедентів.
        НТУУ КПІ ім.І.Сікорського
        Киів-2020
    end footer

@enduml

