@startuml

    |Гість|
    
        start
        
        : Натискає на кнопку "Вхід в систему";
    
    |Система|
    
        : Обробляє запит на вхід;
        : Відправляє форму для заповнення;
    
    |Гість|
    
        : Заповнює поля з даними для авторизації:
        - логін або електронна пошта
        - пароль;
        
    |Система|
        
        : Обробляє введені дані:
        - перевіряє на правильність введення
          адреси (email@domain.com)
        - перевіряє на правильність введення 
          пароля (8+ символів, лише латиниця,
          мінімум 1 велика літера, мінімум 1 цифра);
        note right #ffaaaa
        <b> Можлива
        <b> EX3.1
        end note
        
        : Здійснює пошук користувача
        за електронною адресою та логіном;
        note right #ffaaaa
        <b> Можливі
        <b> EX3.2, EX3.3
        end note
        
        : Створює сеанс роботи;
        
    |Гість|
    
        : Успішний вхід в систему;
        
        stop;
    
right footer
ProjectsLab
НТУУ КПІ ім. І.Сікорського
Киів - 2020
end footer

@enduml