
@startuml
    |Користувач|
        start
        : Натискає на блок артефакту;
    |Система|
        : Повертає модальне \nвікно з обраним артефактом;
        note right #ffaaaa
        <b> Можливо
        <b> EX_AR.1
        end note
        
    |Користувач|
        stop;

    right footer
        Аналітичний портал. Модель прецедентів.
        НТУУ КПІ ім.І.Сікорського
        Киів-2020
    end footer

@enduml

